name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image locally
        # Додаємо 'cd назва_папки &&' перед збіркою
        run: cd app && docker build -t shop-zara --build-arg DEV=true .

      - name: Run Tests
        # Додаємо 'cd назва_папки &&' перед тестами (оскільки код теж там)
        run: cd app && docker run shop-zara sh -c "python manage.py test"

  deploy:
    name: Deploy to Render
    needs: build-and-test
    runs-on: ubuntu-latest
    # Деплой відбувається ТІЛЬКИ якщо тести пройшли успішно
    steps:
      - name: Trigger Render Deployment
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
